name 'hbase'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures hbase'
long_description 'Installs/Configures hbase'
version '0.1.0'
depends 'hadoop'
